apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: nguyentanthanh0709/chat-service:latest
          ports:
            - containerPort: 8181
          env:
            - name: NODE_ENV
              value: development
            - name: MONGO_DB_URI
              value: mongodb://mongo:27017/ChatDB
            - name: PORT
              value: "8181"
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: USER_SERVICE_BASE_URL
              value: http://user-service
            - name: CLIENT_ORIGIN
              value: http://localhost
          resources:
              limits:
                memory: 512Mi
                cpu: 400m
              requests:
                memory: 256Mi
                cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: microservices
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8181

