apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nguyentanthanh0709/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8180
          env:
            - name: NODE_ENV
              value: development
            - name: DB_HOST
              value: mysql.microservices.svc.cluster.local
            - name: DB_USERNAME
              value: rootuser
            - name: DB_PASSWORD
              value: pass
            - name: DB_DATABASE
              value: user
            - name: DB_PORT
              value: "3306"
            - name: CHAT_SERVICE_BASE_URL
              value: http://chat-service
            - name: CLIENT_ORIGIN
              value: http://localhost
            - name: PORT
              value: "8180"
          resources:
              limits:
                memory: 256Mi
                cpu: 300m
              requests:
                memory: 128Mi
                cpu: 100m

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8180
